sudo: required
services:
    - docker

before_install:
    - docker build -t gileo/docker-react -f Dockerfile.dev .

script:
    - docker run gileo/docker-react npm run test -- --coverage
    - docker run -e CI=true gileo/docker-react npm run test
